import MovieTicket from "src/assets/frontend/images/ticket/ticket-tab01.png";
import EventsTicket from "src/assets/frontend/images/ticket/ticket-tab02.png";
import SportsTicket from "src/assets/frontend/images/ticket/ticket-tab03.png";

export const timeZones = [
  { label: "ACT", value: "Australia/ACT" },
  { label: "Adelaide", value: "Australia/Adelaide" },
  { label: "Brisbane", value: "Australia/Brisbane" },
  { label: "Broken Hill", value: "Australia/Broken_Hill" },
  { label: "Canberra", value: "Australia/Canberra" },
  { label: "Currie", value: "Australia/Currie" },
  { label: "Darwin", value: "Australia/Darwin" },
  { label: "Eucla", value: "Australia/Eucla" },
  { label: "Hobart", value: "Australia/Hobart" },
  { label: "LHI", value: "Australia/LHI" },
  { label: "Lindeman", value: "Australia/Lindeman" },
  { label: "Lord Howe", value: "Australia/Lord_Howe" },
  { label: "Melbourne", value: "Australia/Melbourne" },
  { label: "NSW", value: "Australia/NSW" },
  { label: "North", value: "Australia/North" },
  { label: "Perth", value: "Australia/Perth" },
  { label: "Queensland", value: "Australia/Queensland" },
  { label: "South", value: "Australia/South" },
  { label: "Sydney", value: "Australia/Sydney" },
  { label: "Tasmania", value: "Australia/Tasmania" },
  { label: "Victoria", value: "Australia/Victoria" },
  { label: "West", value: "Australia/West" },
  { label: "Yancowinna", value: "Australia/Yancowinna" },
];

export const EVENT_TAGS = [
  "Conference",
  "Workshop",
  "Seminar",
  "Webinar",
  "Festival",
  "Concert",
  "Exhibition",
  "Networking",
  "Fundraiser",
  "Sports",
  "Technology",
  "Education",
  "Music",
  "Art",
  "Science",
  "Literature",
  "Business",
  "Health",
  "Sustainability",
  "Innovation",
  "Professionals",
  "Students",
  "Entrepreneurs",
  "Artists",
  "Academics",
  "Families",
  "Youth",
  "General Public",
  "Outdoor",
  "Indoor",
  "Virtual",
  "Local",
  "International",
  "Weekday",
  "Weekend",
  "Evening",
  "Daytime",
  "Free Entry",
  "Ticket Required",
  "Registration Required",
  "Accessible Venue",
  "Live Music",
  "Food and Drinks",
  "Guest Speaker",
  "Workshops",
  "Panels",
  "Q&A Sessions",
];

export const EventStatusEnum = {
  PLANNED: "PLANNED",
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const EVENT_CATEGORIES = [
  { label: "Music & Concerts", value: "music_concerts", isFeatured: true, img: EventsTicket },
  { label: "Fundraisers", value: "fundraisers" },
  { label: "Arts & Culture", value: "arts_culture", isFeatured: true, img: MovieTicket },
  { label: "Sports", value: "sports_fitness", isFeatured: true, img: SportsTicket },
  { label: "Food & Drink", value: "food_drink" },
  { label: "Holiday Events", value: "holiday_events" },
  { label: "Conferences & Seminars", value: "conferences_seminars" },
  { label: "Education & Workshops", value: "education_workshops" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Health & Wellness", value: "health_wellness" },
  { label: "Networking & Social", value: "networking_social" },
  { label: "Technology & Innovation", value: "technology_innovation" },
  { label: "Trade Shows & Expos", value: "trade_shows_expos" },
  { label: "Travel & Adventure", value: "travel_adventure" },
  { label: "Family & Kids", value: "family_kids" },
  { label: "Outdoor & Nature", value: "outdoor_nature" },
  { label: "Community & Civic", value: "community_civic" },
  { label: "Religious & Spiritual", value: "religious_spiritual" },
  { label: "Other", value: "other" },
];
